### ISSUE TITLE
Proportional VGA calibration

### ISSUE THREAD

**Issue by xiongjunwen44** [JQIamo/analog-pi#2]
Hi, 

Our group bought ~10 JQI pi controller v2.5.3 and I'm trying to go through the Initial Calibrations and Tests on p. 14 of the manual. However, I encounter difficulties in the Proportional VGA calibration part.

For step 11 and 12, U9-Pin10 and POT2 are inaccessible once all the front panel controls are connected to the board. I tried connecting the PCB with U9 and POT2 to the board with cables instead, which makes U9 and POT2 accessible. However, the cable connections are not quite reliable given the number of Molex connectors I need to make. Thus, I'm wondering if there's an easier way to access U9 and POT2 once everything is assembled. 

Thanks a lot!

**Comment by dsbarker** [comment]
Hi Junwen,

This is a known issue with the snap-together PCB assembly of the board. Because the documentation was written before the snap-together assembly was developed, the documentation doesn't mention the difficulty in setting up the snap-together boards.

We have some boxes (for older versions of the PCBs) that use ribbon cables to make all the necessary connections so that U9 and POT2 are accessible. We usually install the analog-pi PCB into one of the old boxes for calibration and then move it into a new box with the snap-together components. Of course, that solution has already occurred to you and, without an assembled box, it's not easy to get working.

We may have a spare calibration box that we can send you. I'm not at JQI today, but I can check for one when I'm there tomorrow.

Daniel

**Comment by xiongjunwen44** [comment]
Thanks a lot, Daniel! If there's a spare calibration box available, it
would be the easiest solution thus far I think!

If not, could you maybe send me a picture of the calibration box and the
part numbers for the ribbon cables and connectors if you happen to have
them? That way, it might be easier for me to build one myself. I've been
searching for connectors that match the Molex housings and headers but
haven't found any yet. Thanks so much for your help!

Best,
Junwen

**Comment by dsbarker** [comment]
I sent you an e-mail with pictures of the calibration box and some suggestions.

**Comment by dsbarker** [comment]
Closed with commit https://github.com/JQIamo/analog-pi/commit/e8bcea54c6d4ed05e0ef3ee88577ae0c8bdc9aef

I've added windows in the shield PCB to allow access to the potentiometers and U9.
