### ISSUE TITLE
INPUT OFFSET en/dis jumper on the board

### ISSUE THREAD

**Issue by xiongjunwen44** [JQIamo/analog-pi#3]
Hi,

Thanks a lot for the help with the connectors last time! Sorry I have another question. So, we ordered 10 jqi lockboxes in total. When I was building them, 3 of them broke. 

For the first one, the OUTPUT OFFSET cannot adjust the OUTPUT MONITOR at the unlock mode. However, the HIGH LIMIT is able to decrease the OUTPUT MONITOR readings. For the second one, the OUTPUT OFFSET again could not adjust the OUTPUT MONITOR at the unlock mode. And, the HIGH LIMIT cannot decrease the OUTPUT MONITOR readings either. For the first two boards, the boards get really hot when plugged in. 

For the third one, most things are correct. However, at the Proportional VGA calibration step, the POT1 (P_VGA_IN_TRIM) cannot adjust the output of VGA(U9-PIN10). And for the square wave reference test, increasing P_GAIN cannot smooth the transition edge. 

We think the three boards broke because the jumper for INPUT OFFSET was not connected initially (which is not indicated in the manual!) or was badly made. To fix the boards, we try measuring the voltage at the 4 regulators, which function properly as the PI_Schematic indicates. Sorry for asking. But, do you have any ideas how we might be able to fix it? And whether the jumper is really the problem?
![IMG_7460](https://user-images.githubusercontent.com/32970730/74977718-1d71d300-53e0-11ea-9c8f-a3dbed5e1c13.jpg)

Best,
Junwen

**Comment by dsbarker** [comment]
Hi Junwen,

The high and low limits must be set such that the output offset is between them at all times. Otherwise the boards will behave strangely. I would suggest powering off both of the first two boards, maximizing/minimizing the high/low limits, setting the output offset pot to the middle of it's range (5, 0 if you're using an indicating dial), repowering the board and trying the adjustments again.

The offset jumper is another feature that was added after the manual was written. The solder bridge in the picture should work fine. Digikey also sells jumpers that you can use (I'll send the part number later).

I'm not sure what's wrong with the other board, but I'll think about it and try to get back to you tomorrow.

**Comment by dsbarker** [comment]
If you don't want to solder-bridge the input offset jumper, you can use S3404-ND. I'm not sure that failing to place the input offset jumper would cause the PCBs to fail.

The regulators can source quite a bit of current. They'll probably still work even if an IC is dead. Is any one of the regulators particularly hot?

For all the broken boards, please check if any of the op amp ICs are very hot. If any IC is hot enough to cause pain when you touch it, then it probably needs to be replaced. I use a reworking station (e.g. the BK4050 from circuit specialists) to remove and place multipin components. You'll need some solder paste as well.

For the third board, since the VGA input trim is not working, I would guess that either U8 or U9 is dead. What is the voltage at U9, pin 10? Does the voltage change when you go to locked mode (you'll need to test this with a scope since there's no P gain at DC)? Does the VGA output trim do anything?

**Comment by xiongjunwen44** [comment]
Hi Daniel,

Thanks a lot for the reply! I think for the first two boards, U27 and U29 are not functioning properly. When U27 IN+ is set to around 6V, its OUT is -12V. There's a +20V increase across the D8B and U27 IN- was set to around 8V. The current is flowing backwards across the diode. For U29, when IN+ is set to -6V, U29 OUT sets U29 IN- to +10V instead. Both U29 and U27 are powered properly. 

For the third board, I think the main issue is that R83 is missing from the board. The voltage range for POT10 is thus from -5V to -5V and the proportional gain cannot actually be increased. 

I might try to find the soldering station you recommend, put on R83 and replace U27 and U29. I'll also order the jumper connectors you recommend. Do you have a better idea why U27 and U29 are not functioning properly? Are they broken because some other part of the circuits? Or they're broken because the Lim- is higher than Lim+ when they were first powered? Hope to find a way to avoid the issue.

Best,
Junwen

**Comment by dsbarker** [comment]
I don't think anyone has ever tracked down the exact limit settings that are needed to damage the board. With luck, we'll get to the bottom of it this time.

I took a look at the output limiting section of the schematic. Based on your description of the problem on the first two boards, U27 is probably fine. The operation that you describe is normal when OUT_LO_LIMIT is set higher than OUT_HI_LIMIT. The differential voltage across U27's inputs is within spec. 

It does sound like U29 is malfunctioning, since it should servo its IN- to match IN+... A 2 V drop across R91 is quite large. It suggests that U28's IN+ is not acting as a high impedance. If U28 OUT is at 8 V, then a large current is flowing from U29 through D6A/D6B into U28. I'm not sure how such a situation would develop, but it could be enough to damage both U28 and U29.

Things to check:
1. Is R91 a 10 kOhm resistor as it should be?
2. Is U29 or U28 hot (enough to burn you or make a damp q-tip sizzle)?
3. What is the voltage at U17 OUT (pin 6)?
4. What is the output offset (U22, pin 6)?

I would guess that replacing U28, U29, and (perhaps) D6 will fix the problem. Provided that you set LIM+ > OUT_OFFSET > LIM- before repowering the boards.

**Comment by xiongjunwen44** [comment]
Thanks a lot for the reply! I have replaced U28 and U29 and the board is working right now. I think I'll be more cautious setting the high and low limits before turning on the board next time.

**Comment by dsbarker** [comment]
After discussing with other JQI electronics people, it seems like the problem is due to the limits being allowed to go all the way to the supply rails. If there were voltage-limiting resistors in line with POT12 and POT13, then the problem could be resolved. The LM7171 op amp (U28 and U29) can only source/sink 100 mA. If LIM- = 12 V and LIM+ = -12 V then the two op amps will sink too much current and damage themselves.

If LIM-/LIM+ were limited to +/- 6 V by inserting limiting resistors, then I think the bug would be resolved. Something to think about for future updates (or hacking into the current board in future production runs).

**For people setting up new boards:** I recommend using a multimeter to ensure that POT12, pin 2 is shorted to the 12 V rail (and that POT13, pin 2 is shorted to the -12 V rail) before powering up the the PI board. You'll probably need to do this test before installing the PCB into the box.
